# Generated by Django 4.2.2 on 2024-12-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEYV', '0010_tipoproducto_alter_producto_tipo_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='ID_pago',
            field=models.IntegerField(),
        ),
    ]
