# Generated by Django 4.2.2 on 2024-12-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEYV', '0011_alter_venta_id_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='ID_Factura',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ID_mediopago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ID_producto',
        ),
    ]
